#!name=iTunes – Mở Khóa Tính Năng VIP
#!desc=Tổng hợp plugin mở khóa các tính năng trong hệ sinh thái iTunes. Vào phần "Cài đặt" để chọn script từ các tác giả gốc tương ứng.
#!author=chxm1023, ddgksf2013, Guding88, Yu9191
# 💬 Discord: https://discord.gg/juY9tw5AJY
# 🚀 Released by: Nightmarket Server

[Script]
# chxm1023
[iTunes]解锁会员系列 = type=http-response, pattern=^https?:\/\/buy\.itunes\.apple\.com\/verifyReceipt$, script-path=https://raw.githubusercontent.com/chxm1023/Rewrite/main/iTunes.js, requires-body=true

# ddgksf2013
[iTunes]解锁会员系列 = type=http-response, pattern=^https?:\/\/buy\.itunes\.apple\.com\/verifyReceipt$, script-path=https://gist.githubusercontent.com/ddgksf2013/9e0f6c7341beea09a31aa309d9d7f502/raw/buyitunes.js, requires-body=true

# Guding88
[iTunes]解锁会员系列 = type=http-response, pattern=^https?:\/\/buy\.itunes\.apple\.com\/verifyReceipt$, script-path=https://raw.githubusercontent.com/Guding88/Script/main/APPheji_iTunes.js, requires-body=true

[MITM]
hostname = %APPEND% buy.itunes.apple.com