#!name=Vivacut
#!desc=Vivacut解锁会员
# 💬 Discord: https://discord.gg/juY9tw5AJY
# 🚀 Released by: Nightmarket Server
#!homepage=https://whatshub.top
#!icon=https://raw.githubusercontent.com/deezertidal/private/main/icons/vivacut.png

[Script]
Vivacut=type=http-response,pattern=^https:\/\/medi\.dxzzy321\.top\/api\/rest\/commerce\/integrate\/vip\/perform,requires-body=1,script-path=https://raw.githubusercontent.com/89996462/Quantumult-X/main/ycdz/vivacut.js

[MITM] 
hostname = %APPEND% medi.dxzzy321.top

#!author=89996462
